<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ProjectP1L0T_Game_Setup</AssemblyName>
    <RootNamespace>ProjectP1L0TGameSetup</RootNamespace>
  </PropertyGroup>
</Project>
